default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: portfolio_dev
  pool: 5
  username: portfolio2
  password: woot

test:
  adapter: postgresql
  encoding: unicode
  database: portfolio_test
  pool: 5
  username: portfolio2
  password: woot